### ISSUE TITLE
Paquete npm desactualizado

### ISSUE THREAD

**Issue by pablomarambio** [pablomarambio/jquery.rut#7]
El [paquete de nodejs](https://www.npmjs.com/package/jquery.rut) que subió @JonDostoy a npm está desactualizado. Podrías actualizarlo, plis?? :smiley:

**Comment by JonDotsoy** [comment]
Ok @pablomarambio  estoy en ello. Por favor indicame tu username en npm. para futuros cambios.

**Comment by JonDotsoy** [comment]
Actualizado a [**v1.1.2**](https://www.npmjs.com/package/jquery.rut/)
